#
# prop-overrides.mk - GENERATED by scripts/para2prop.py --mk. DO NOT EDIT.
#
# Android properties derived from harmony/param/ohos.para, injected into the
# build. Device identity and TWRP runtime values become system props
# (PRODUCT_PROPERTY_OVERRIDES); the security/debug values are product props
# (PRODUCT_PRODUCT_PROPERTIES) because build/make already assigns them to
# ADDITIONAL_SYSTEM_PROPERTIES. All of these end up, last-wins, in the
# generated recovery/root/prop.default.
#
# Make list entries cannot contain whitespace, so .para values with spaces
# (the product name and software version) are skipped here and only appear in
# harmony/prop.default for reference.
#

PRODUCT_PROPERTY_OVERRIDES += \
    ro.product.model=Kirin9010 \
    ro.product.manufacturer=HUAWEI \
    ro.product.brand=HUAWEI \
    ro.ohos.devicetype=pad \
    ro.ohos.hardwareversion=Kirin9010 \
    ro.product.cpu.abilist=arm64-v8a \
    ro.build.characteristics=default \
    ro.ohos.secure=1 \
    ro.ohos.debuggable=0 \
    ro.recovery.mode=1 \
    ro.hardware=kirin \
    ro.boot.ufs=fa500000.ufs \
    ro.usb.controller=efc00000.dwc3 \
    ro.product.device=kirin9010 \
    ro.product.cpu.abi=arm64-v8a \
    ro.sf.lcd_density=320 \
    ro.usb.vid=0x12D1 \
    ro.usb.pid=0x5000 \
    ro.recovery.usb.mode=hdc

# Platform-owned security props: see TWRP_RUNTIME_PRODUCT.
PRODUCT_PRODUCT_PROPERTIES += \
    ro.secure=0 \
    ro.debuggable=1 \
    ro.adb.secure=0 \
    ro.allow.mock.location=0
