#!/bin/bash
# bundle-hdc.sh - assemble the self-contained hdcd runtime and generate the
# makefile fragment that installs it into the recovery ramdisk.
#
# HarmonyOS HDC uses a device-side daemon, `hdcd`, which is a musl/OHOS binary
# and therefore cannot run under TWRP's bionic userspace. This bundles `hdcd`,
# the musl loader and its library closure (about 12 MiB) so recovery can run it
# through the bundled loader, and wires those files into PRODUCT_COPY_FILES.
#
# Nothing proprietary is stored in the repository. Point HDC_SOURCE at a stock
# OpenHarmony image (or an already-extracted ramdisk tree) that you own:
#
#   HDC_SOURCE=updater_ramdisk.img ./scripts/bundle-hdc.sh
#   HDC_SOURCE=/path/to/extracted-ramdisk ./scripts/bundle-hdc.sh
#   ./scripts/bundle-hdc.sh updater_ramdisk.img
#
# Output:
#   prebuilt/hdc/...            the runtime (git-ignored)
#   harmony/hdc/hdc-prebuilt.mk generated install fragment (committed)
#
# Without this step the build still succeeds; recovery simply starts without
# HDC, and scripts/hdc-usb.sh exits cleanly.

set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${HERE}/prebuilt/hdc"
MK="${HERE}/harmony/hdc/hdc-prebuilt.mk"

SRC="${HDC_SOURCE:-${1:-}}"
if [ -z "${SRC}" ]; then
    echo "usage: HDC_SOURCE=<stock image|extracted dir> $0" >&2
    exit 2
fi
if [ ! -e "${SRC}" ]; then
    echo "!!! HDC_SOURCE not found: ${SRC}" >&2
    exit 2
fi

mkdir -p "${OUT}"

if [ -d "${SRC}" ]; then
    python3 "${HERE}/scripts/hdc_extract.py" --dir "${SRC}" --out "${OUT}"
else
    python3 "${HERE}/scripts/hdc_extract.py" --image "${SRC}" --out "${OUT}"
fi

MANIFEST="${OUT}.manifest"
if [ ! -f "${MANIFEST}" ]; then
    echo "!!! extraction did not produce ${MANIFEST}" >&2
    exit 1
fi

# Generate the install fragment from the manifest, so files that are no longer
# part of the bundle are never installed (nothing is deleted from disk).
mkdir -p "$(dirname "${MK}")"
{
    echo "# GENERATED by scripts/bundle-hdc.sh - do not edit."
    echo "# Installs the bundled hdcd musl runtime into the recovery ramdisk."
    echo "PRODUCT_COPY_FILES += \\"
    while IFS= read -r rel; do
        [ -n "${rel}" ] || continue
        echo "    \$(LOCAL_PATH)/prebuilt/hdc/${rel}:recovery/root/ohos-hdc/${rel} \\"
    done < "${MANIFEST}"
    echo ""
} > "${MK}"

count="$(grep -c . "${MANIFEST}")"
size="$(du -sh "${OUT}" | cut -f1)"
echo ">>> bundled ${count} files (${size}) -> ${OUT}"
echo ">>> install fragment -> ${MK}"
