#!/usr/bin/env python3
"""para2prop.py - derive TWRP's prop.default from the HarmonyOS ohos.para file.

HarmonyOS parameters (`.para`, `const.*` / `ohos.boot.*`, read by the param
service) and Android properties (`prop.default`, `ro.*`, read by TWRP's init)
are two different systems. To keep them from drifting, the `.para` file is the
single source of truth for device identity and this script translates it into
the Android properties that TWRP needs.

Anything that is genuinely recovery-runtime specific (the device codename,
root adb, LCD density, USB ids) has no HarmonyOS counterpart and is emitted as
a static block. The stock `const.secure=1` / `const.debuggable=0` describe the
secure HarmonyOS system, so they are preserved under `ro.ohos.*` instead of
being copied onto `ro.secure` / `ro.debuggable`, which recovery needs opposite.

Usage:
    scripts/para2prop.py harmony/param/ohos.para -o harmony/prop.default
    scripts/para2prop.py harmony/param/ohos.para            # stdout
"""

import argparse
import sys

# HarmonyOS parameter -> Android property. Values flow through verbatim.
MAPPING = {
    "const.product.name": "ro.product.name",
    "const.product.model": "ro.product.model",
    "const.product.manufacturer": "ro.product.manufacturer",
    "const.product.brand": "ro.product.brand",
    "const.product.devicetype": "ro.ohos.devicetype",
    "const.product.hardwareversion": "ro.ohos.hardwareversion",
    "const.product.cpu.abilist": "ro.product.cpu.abilist",
    "const.product.software.version": "ro.ohos.software.version",
    "const.build.characteristics": "ro.build.characteristics",
    "const.secure": "ro.ohos.secure",
    "const.debuggable": "ro.ohos.debuggable",
    "const.recovery.mode": "ro.recovery.mode",
    "ohos.boot.hardware": "ro.hardware",
    "ohos.boot.ufs": "ro.boot.ufs",
    "ohos.boot.usb.controller": "ro.usb.controller",
}

# Recovery-runtime properties with no HarmonyOS source. These go to
# PRODUCT_PROPERTY_OVERRIDES (system/build.prop). ro.product.board and
# ro.board.platform are deliberately absent: build/make derives them from
# TARGET_BOOTLOADER_BOARD_NAME / TARGET_BOARD_PLATFORM (set in BoardConfig.mk)
# and injecting them too would collide in the same build.prop.
TWRP_RUNTIME = {
    "ro.product.device": "kirin9010",
    "ro.product.cpu.abi": "arm64-v8a",
    "ro.sf.lcd_density": "320",
    "ro.usb.vid": "0x12D1",
    "ro.usb.pid": "0x5000",
    # HarmonyOS HDC (Device Connector) transport: hdc | dual | adb.
    "ro.recovery.usb.mode": "hdc",
}

# Security/debug properties that build/make also assigns in
# ADDITIONAL_SYSTEM_PROPERTIES (core/main.mk: ro.secure=1, ro.debuggable=1,
# ro.allow.mock.location=0 for userdebug). Injecting them as system props makes
# post_process_props fail with "found duplicate sysprop assignments:
# ro.secure=0 / ro.secure=1". They go to PRODUCT_PRODUCT_PROPERTIES instead:
# product/etc/build.prop is concatenated *after* system/build.prop when
# recovery/root/prop.default is assembled, so recovery still ends up with these
# values while each individual build.prop stays conflict-free.
TWRP_RUNTIME_PRODUCT = {
    "ro.secure": "0",
    "ro.debuggable": "1",
    "ro.adb.secure": "0",
    "ro.allow.mock.location": "0",
}

HEADER = """\
#
# prop.default - GENERATED by scripts/para2prop.py. DO NOT EDIT BY HAND.
#
# Source of truth : harmony/param/ohos.para
# HarmonyOS identity is translated from the .para file; the trailing block is
# recovery-runtime state that HarmonyOS has no equivalent for. Regenerate with:
#     scripts/para2prop.py harmony/param/ohos.para -o harmony/prop.default
#
"""

# The build system generates recovery/root/prop.default itself (from the
# partition build.prop files), so shipping our own copy would collide with that
# rule ("overriding commands for target ... recovery/root/prop.default"). These
# properties are injected into the build instead and end up in the generated
# file via system/build.prop.
MK_HEADER = """\
#
# prop-overrides.mk - GENERATED by scripts/para2prop.py --mk. DO NOT EDIT.
#
# Android properties derived from harmony/param/ohos.para, injected into the
# build. Device identity and TWRP runtime values become system props
# (PRODUCT_PROPERTY_OVERRIDES); the security/debug values are product props
# (PRODUCT_PRODUCT_PROPERTIES) because build/make already assigns them to
# ADDITIONAL_SYSTEM_PROPERTIES. All of these end up, last-wins, in the
# generated recovery/root/prop.default.
#
# Make list entries cannot contain whitespace, so .para values with spaces
# (the product name and software version) are skipped here and only appear in
# harmony/prop.default for reference.
#
"""


def parse_para(path):
    params = {}
    with open(path, "r", encoding="utf-8") as handle:
        for lineno, raw in enumerate(handle, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                print(f"warning: {path}:{lineno}: skipping malformed line",
                      file=sys.stderr)
                continue
            key, _, value = line.partition("=")
            key, value = key.strip(), value.strip()
            if len(value) >= 2 and value[0] == value[-1] == '"':
                value = value[1:-1]
            params[key] = value
    return params


def render(params):
    lines = [HEADER.rstrip("\n"), ""]
    lines.append("# --- derived from ohos.para ---")
    for para_key, prop in MAPPING.items():
        if para_key in params:
            lines.append(f"{prop}={params[para_key]}")
    lines.append("")
    lines.append("# --- TWRP recovery runtime ---")
    for prop, value in TWRP_RUNTIME.items():
        lines.append(f"{prop}={value}")
    lines.append("")
    lines.append("# --- recovery security (overrides the userdebug defaults) ---")
    for prop, value in TWRP_RUNTIME_PRODUCT.items():
        lines.append(f"{prop}={value}")
    return "\n".join(lines) + "\n"


def render_mk(params):
    """Emit the make fragment that injects these props into the build."""
    system = []
    for para_key, prop in MAPPING.items():
        value = params.get(para_key)
        if value is None:
            continue
        if any(char.isspace() for char in value):
            print(f"note: skipping {prop} (value has whitespace: {value!r}); "
                  f"see harmony/prop.default", file=sys.stderr)
            continue
        system.append((prop, value))
    for prop, value in TWRP_RUNTIME.items():
        if any(char.isspace() for char in value):
            continue
        system.append((prop, value))

    def block(var, entries):
        out = [f"{var} += \\"]
        for index, (prop, value) in enumerate(entries):
            suffix = " \\" if index < len(entries) - 1 else ""
            out.append(f"    {prop}={value}{suffix}")
        return out

    lines = [MK_HEADER.rstrip("\n"), "", *block("PRODUCT_PROPERTY_OVERRIDES", system)]
    lines.append("")
    lines.append("# Platform-owned security props: see TWRP_RUNTIME_PRODUCT.")
    lines.extend(block("PRODUCT_PRODUCT_PROPERTIES",
                       list(TWRP_RUNTIME_PRODUCT.items())))
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("para", help="path to ohos.para")
    ap.add_argument("-o", "--output", help="output file (default: stdout)")
    ap.add_argument("--mk", metavar="FILE",
                    help="also write a PRODUCT_PROPERTY_OVERRIDES make fragment")
    args = ap.parse_args()

    params = parse_para(args.para)

    rendered = render(params)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(rendered)
    else:
        sys.stdout.write(rendered)

    if args.mk:
        with open(args.mk, "w", encoding="utf-8") as handle:
            handle.write(render_mk(params))
    return 0


if __name__ == "__main__":
    sys.exit(main())
