#!/usr/bin/env python3
"""para2prop.py - derive TWRP's prop.default from the HarmonyOS ohos.para file.

HarmonyOS parameters (`.para`, `const.*` / `ohos.boot.*`, read by the param
service) and Android properties (`prop.default`, `ro.*`, read by TWRP's init)
are two different systems. To keep them from drifting, the `.para` file is the
single source of truth for device identity and this script translates it into
the Android properties that TWRP needs.

Anything that is genuinely recovery-runtime specific (the device codename,
root adb, LCD density, USB ids) has no HarmonyOS counterpart and is emitted as
a static block. The stock `const.secure=1` / `const.debuggable=0` describe the
secure HarmonyOS system, so they are preserved under `ro.ohos.*` instead of
being copied onto `ro.secure` / `ro.debuggable`, which recovery needs opposite.

Usage:
    scripts/para2prop.py harmony/param/ohos.para -o harmony/prop.default
    scripts/para2prop.py harmony/param/ohos.para            # stdout
"""

import argparse
import sys

# HarmonyOS parameter -> Android property. Values flow through verbatim.
MAPPING = {
    "const.product.name": "ro.product.name",
    "const.product.model": "ro.product.model",
    "const.product.manufacturer": "ro.product.manufacturer",
    "const.product.brand": "ro.product.brand",
    "const.product.devicetype": "ro.ohos.devicetype",
    "const.product.hardwareversion": "ro.ohos.hardwareversion",
    "const.product.cpu.abilist": "ro.product.cpu.abilist",
    "const.product.software.version": "ro.ohos.software.version",
    "const.build.characteristics": "ro.build.characteristics",
    "const.secure": "ro.ohos.secure",
    "const.debuggable": "ro.ohos.debuggable",
    "const.recovery.mode": "ro.recovery.mode",
    "ohos.boot.hardware": "ro.hardware",
    "ohos.boot.ufs": "ro.boot.ufs",
    "ohos.boot.usb.controller": "ro.usb.controller",
}

# Recovery-runtime properties with no HarmonyOS source.
TWRP_RUNTIME = {
    "ro.product.device": "kirin9010",
    "ro.product.board": "kirin9010",
    "ro.product.cpu.abi": "arm64-v8a",
    "ro.board.platform": "kirin",
    "ro.secure": "0",
    "ro.debuggable": "1",
    "ro.adb.secure": "0",
    "ro.allow.mock.location": "0",
    "ro.sf.lcd_density": "320",
    "ro.usb.vid": "0x12D1",
    "ro.usb.pid": "0x5000",
    # HarmonyOS HDC (Device Connector) transport: hdc | dual | adb.
    "ro.recovery.usb.mode": "hdc",
}

HEADER = """\
#
# prop.default - GENERATED by scripts/para2prop.py. DO NOT EDIT BY HAND.
#
# Source of truth : harmony/param/ohos.para
# HarmonyOS identity is translated from the .para file; the trailing block is
# recovery-runtime state that HarmonyOS has no equivalent for. Regenerate with:
#     scripts/para2prop.py harmony/param/ohos.para -o harmony/prop.default
#
"""


def parse_para(path):
    params = {}
    with open(path, "r", encoding="utf-8") as handle:
        for lineno, raw in enumerate(handle, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                print(f"warning: {path}:{lineno}: skipping malformed line",
                      file=sys.stderr)
                continue
            key, _, value = line.partition("=")
            key, value = key.strip(), value.strip()
            if len(value) >= 2 and value[0] == value[-1] == '"':
                value = value[1:-1]
            params[key] = value
    return params


def render(params):
    lines = [HEADER.rstrip("\n"), ""]
    lines.append("# --- derived from ohos.para ---")
    for para_key, prop in MAPPING.items():
        if para_key in params:
            lines.append(f"{prop}={params[para_key]}")
    lines.append("")
    lines.append("# --- TWRP recovery runtime ---")
    for prop, value in TWRP_RUNTIME.items():
        lines.append(f"{prop}={value}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("para", help="path to ohos.para")
    ap.add_argument("-o", "--output", help="output file (default: stdout)")
    args = ap.parse_args()

    rendered = render(parse_para(args.para))
    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(rendered)
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
